### ISSUE TITLE
Incorporate rstudio-server into the image

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/r-docker#162]

**Comment by remlapmot** [comment]
This was closed by #164 but I forgot to link that PR to this issue.

The image has existed since Friday.

We just merged the PR for the accompanying `opensafely rstudio` subcommand (v1.49.0 of CLI)
<https://github.com/opensafely-core/opensafely-cli/pull/272>

We are doing a soft launch, so there's a draft of the addition to the docs for this in this branch of the docs repo
<https://github.com/opensafely/documentation/tree/add-rstudio-cli-subcommand>.
